services:

  powerfactors-assignment-service:
    restart: always
    build:
      context: ./powerfactors-assignment
      dockerfile: deploy/development/Dockerfile.dev
    ports:
      - "40000:40000"
      - ${SERVER_PORT:-8000}:${SERVER_PORT:-8000}
    command: dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient --continue=true exec ./main ${SERVER_ADDRESS:-0.0.0.0} ${SERVER_PORT:-8000}
    volumes:
      - ./powerfactors-assignment:/app
      
      
     
