FROM golang:1.20.2-alpine3.16 as builder

RUN apk update
RUN apk add git

WORKDIR /app

#COPY go.mod go.sum ./

#RUN go mod download
RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM golang:1.20.2-alpine3.16

RUN apk update
RUN apk add build-base

COPY --from=builder /go /go

WORKDIR /powerfactors-assignment/cmd

COPY . .

RUN GOOS=linux go build -gcflags='all=-N -l' -tags musl -a -installsuffix cgo -o main ./cmd/main.go

EXPOSE 40000

